### PR TITLE
#1406 Handle Empty State for DataTable

### PR DESCRIPTION
**Pull request by TheHadiAhmadi**

### CODE REVIEW

**Comment by pournasserian** [comment]
@TheHadiAhmadi why we should add `ColumnsFragment`. There is another solution and we will implement that later.

**Comment by TheHadiAhmadi** [comment]
@pournasserian We can use ChildContent but I added ColumnsFragment because this name shows better what should be placed inside of it.later we would have Loading fragment, filters fragment, pagingFragment....

**Comment by pournasserian** [comment]
@TheHadiAhmadi this PR has conflict. Resolve that and then I will review.

**Comment by TheHadiAhmadi** [comment]
@pournasserian Ok

**Comment by pournasserian** [comment]
In order to handle empty state, why we should render inside DataTable component? How about this implementation:

```
<DataTable Items="Roles" Visisble=@(Roles.Count > 0)>
    <DataTableItem Label="Name">@context.Name</DataTableItem>
    <DataTableItem Label="Description">@context.Description</DataTableItem>
    <DataTableItem>
        <div class="flex gap-2">
            <Button Color="Color.Primary" Href="@GetUrl("Update Role", new { id = @context.Id })" Size="ButtonSize.Small">
                <Icon Name="IconName.Edit" />Edit
            </Button>
            <Button Color="Color.Danger" Outline @onclick="() => OnConfirm(context)" Size="ButtonSize.Small">
                <Icon Name="IconName.Delete" />Delete
            </Button>
        </div>
    </DataTableItem>
</DataTable>
<EmptyState Visisble=@(Roles.Count == 0)>
....
</EmptyState>
```

**Pull request closed without merging**
