### PR TITLE
fix: apps update api throws exception

### PR DESCRIPTION
**Pull request by ParsaGachkar**
We are not working with id for updates and there is no way to map the id from Dto.

### CODE REVIEW

**Comment by pournasserian** [comment]
@ParsaGachkar What if we change the app's slug (if slug is defined in other app or not defined)?

**Comment by ParsaGachkar** [comment]
> @ParsaGachkar What if we change the app's slug (if slug is defined in other app or not defined)?

I thought slug is supposed to be static after creation, Current signature for `Update` action in `AppController` does not allow such change that why i assumed Slug is sposed to be static.

```csharp
public async Task<IApiResult<AppResponse>> Update([FromBody] AppUpdateRequest request, CancellationToken cancellationToken = default)
```

```csharp
public class AppUpdateRequest
{
    public string Title { get; set; } = default!;
    public string? Description { get; set; }
    public string Slug { get; set; } = default!;
}
```

**Comment by pournasserian** [comment]
@ParsaGachkar you are right: App Slug shouldn't be changed after creation. Please apply previous update

**Comment by ParsaGachkar** [comment]
done

**Pull request closed without merging**
