### PR TITLE
346 develop e2e tests for host apis

### LINKED ISSUE #346: Develop E2E Tests for `Host` Apis

### LINKED ISSUE #440: E2E Tests Structure

### PR DESCRIPTION
**Pull request by ParsaGachkar**
Closes #346 
Closes #440

### CODE REVIEW

**Comment by pournasserian** [comment]
@ParsaGachkar please resolve the conflict

**Comment by pournasserian** [comment]
1. It seems that there are some un-used Nuget packages.
2. Tests not passed for second time.

image

**Comment by ParsaGachkar** [comment]
> 1. It seems that there are some un-used Nuget packages.
> 2. Tests not passed for second time.
> 
> image

My bad issue was caused by conflicting Tests. We should DisableTestParallelization because we are not running each scenario in an isolated envirnoment.

**Comment by pournasserian** [comment]
It has compellation error
image

**Review by pournasserian — APPROVED** [review]

**Pull request merged**
