### PR TITLE
1265 fileupload review

### PR DESCRIPTION
**Pull request by ParsaGachkar**
- **refactor: add ErrorCode related to File**
- **feat: implement `FileEntity`**
- **feat: implement `FileRepository` for mongodb**
- **feat: implement `LocalFileSystemProvider`**
- **feat: implement `FileController` and its related Dtos**
- **feat: implement `File` dto mappings**
- **feat: add `LocalFileSystemProvider` to dependency injection**

### CODE REVIEW

**Comment by pournasserian** [comment]
@ParsaGachkar why Fileaentity derived from Entity (not audit entity)

Why we have route attribute on controller

**Comment by pournasserian** [comment]
CancellationToken!!!
Why the repository interface is IEntityRepository?

**Comment by ParsaGachkar** [comment]
sorry for the inconvenience!

**Comment by babakhani** [comment]
@ParsaGachkar 
this pull request contains so many commits, please review and clean your commits before applying pull requests.

**Pull request closed without merging**
