### PR TITLE
89 implement file management feature

### LINKED ISSUE #89: Implement File management feature
Flat Virtual File System to keep track of files

### PR DESCRIPTION
**Pull request by ParsaGachkar**
closes #89

### CODE REVIEW

**Comment by pournasserian** [comment]
@ParsaGachkar it seems that Slug property is not useful. The files will be accessible by Guid for now. Remove Slug and related methods.

**Comment by ParsaGachkar** [comment]
> @ParsaGachkar it seems that Slug property is not useful. The files will be accessible by Guid for now. Remove Slug and related methods.

removed!

it was a solution for reza's concern for random urls.

**Comment by pournasserian** [comment]
@ParsaGachkar this PR is very bad!!!
- Why you didn't write cancellationtoken in the API and others?
- Why using localpath property?
- Default upload path should be in one level upper than wwwroot which is won't be accessible by web users to download directly by calling the URL 
- Change GetFiles method name to GetAll (like other controllers)
- Does the code works for multipart files or large files?

**Comment by ParsaGachkar** [comment]
> @ParsaGachkar this PR is very bad!!!
> 
> * Why you didn't write cancellationtoken in the API and others?
> * Why using localpath property?
> * Default upload path should be in one level upper than wwwroot which is won't be accessible by web users to download directly by calling the URL
> * Change GetFiles method name to GetAll (like other controllers)
> * Does the code works for multipart files or large files?

- [*] added missing `cancellationtoken`s
- [*] unnecessary `localpath` removed from service
- [*] `GetFiles` renamed to `GetAll`

**Comment by ParsaGachkar** [comment]
> * Default upload path should be in one level upper than wwwroot which is won't be accessible by web users to download directly by calling the URL

The files are not currently located in the `wwwroot` directory; they are accessible solely via their unique identifier using the following API endpoint: `GET: /api/File/GetFileById/{id}`.

Are you suggesting that the files should be uploaded to the `/wwwroot/uploaded` directory?

It is possible to access the files directly via URL. However, please note that their `Content-Type` and `FileName` may not be set accurately, as they lack a valid file extension.

**Comment by ParsaGachkar** [comment]
I am currently enhancing our file upload endpoint based on the guidance provided in the article [Upload large files with streaming](https://learn.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-8.0). It is important to avoid using IFormFile due to potential excessive resource consumption.

**Comment by pournasserian** [comment]
@ParsaGachkar change GetFileById to GetById.

We need Download method as well

**Comment by pournasserian** [comment]
@ParsaGachkar rename DeleteById to Delete.

Where is single file upload method? We need two methods for upload: 
- Single file upload
- Multiple file uploads

**Comment by ParsaGachkar** [comment]
I'm using `SingleFileCreateRequest` and `MultipleFileCreateRequest` for our single and multiple file request models

**Comment by pournasserian** [comment]
@ParsaGachkar are you still working on this?

**Comment by ParsaGachkar** [comment]
@pournasserian i was waiting for review and merge

**Pull request closed without merging**
