### PR TITLE
573 nswag is using incorrect types with datetime fields

### PR DESCRIPTION
**Pull request by ParsaGachkar**

### CODE REVIEW

**Comment by pournasserian** [comment]
@ParsaGachkar It has build error! I created & merged another PR #582

**Comment by pournasserian** [comment]
@ParsaGachkar 
image

**Comment by ParsaGachkar** [comment]
image
i cant regenerate clients swagger json is empty

**Comment by ParsaGachkar** [comment]
fixed! clients are regenerated

**Pull request merged**
