### PR TITLE
340 develop litedb repository from new abstracts 1

### PR DESCRIPTION
**Pull request by ParsaGachkar**

### CODE REVIEW

**Comment by pournasserian** [comment]
@ParsaGachkar develop ApiTokenRepository

Also, in file 

what are these lines:
```
<ItemGroup>
      <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
        <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.4\Microsoft.Extensions.DependencyInjection.Abstractions.dll</HintPath>
      </Reference>
    </ItemGroup>
```
Also, comments on `ConfigureBsonSerializers` method.

Should we set both connectionstrings in config?

Should we change default db from MongoDB to Litedb?

**Comment by ParsaGachkar** [comment]
@pournasserian looks like we dont need custom mappings for Decimal, Decimal?, and Guid https://www.litedb.org/docs/object-mapping/

**Comment by pournasserian** [comment]
@ParsaGachkar LiteDB does not exist in the solution
image

**Comment by ParsaGachkar** [comment]
> @ParsaGachkar LiteDB does not exist in the solution image

I apologize for the oversight. it is fixed

**Review by pournasserian — APPROVED** [review]

**Pull request merged**
